FROM denoland/deno:debian-2.4.3

WORKDIR /app
ENV DENO_DIR=/deno-dir

RUN apt-get update && \
    apt-get install -y curl bash watchman && \
    curl -L https://github.com/watchexec/watchexec/releases/download/v2.3.2/watchexec-2.3.2-aarch64-unknown-linux-musl.deb \
    -o /tmp/watchexec.deb && \
    apt install -y /tmp/watchexec.deb && \
    rm /tmp/watchexec.deb

RUN curl -L https://github.com/tailwindlabs/tailwindcss/releases/download/v4.1.11/tailwindcss-linux-arm64 \
    -o /usr/bin/tailwindcss && \
    chmod +x /usr/bin/tailwindcss

COPY deno.jsonc ./

CMD ["task", "start"]